version: '3.1'

volumes:
  pg_selectel:

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=selectel
      - POSTGRES_USER=selectel
      - POSTGRES_DB=selectel
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432
#  pg_db2:
#    image: postgres
#    restart: always
#    environment:
#      - POSTGRES_PASSWORD=user
#      - POSTGRES_USER=user
#      - POSTGRES_DB=user
#    volumes:
#      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
#    ports:
#      - ${POSTGRES_PORT:-5433}:5433
